/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArtistResponse } from './artist-response';


export interface AlbumResponse { 
    id?: string;
    title?: string;
    artist?: ArtistResponse;
    coverUrl?: string;
    releaseDateTime?: string;
    /**
     * True once the scheduled release time has passed (visible to public). False while still scheduled in the future.
     */
    released?: boolean;
    totalStreams?: number;
    /**
     * Number of songs in this album (computed)
     */
    songCount?: number;
    /**
     * Station this album belongs to (null if not assigned)
     */
    stationId?: string;
    /**
     * Display name of the station (null if not assigned)
     */
    stationName?: string;
}

