/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AlbumRequest { 
    title: string;
    artistId: string;
    coverUrl: string;
    /**
     * Scheduled release timestamp. Albums become public when this moment passes (the scheduler flips `released` to true).
     */
    releaseDateTime: string;
    /**
     * Optional station this album belongs to (drives \"Escucha en [station]\" in album detail)
     */
    stationId?: string;
}

