/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AlbumResponse } from './album-response';


export interface AlbumPage { 
    content?: Array<AlbumResponse>;
    totalElements?: number;
    totalPages?: number;
    page?: number;
    size?: number;
}

