/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ArtistInternalDto { 
    id?: string;
    name?: string;
    photoUrl?: string;
    monthlyListeners?: number;
}

