/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ArtistResponse { 
    id?: string;
    name?: string;
    photoUrl?: string;
    bio?: string;
    monthlyListeners?: number;
    followersCount?: number;
    isTop?: boolean;
    /**
     * Registration date shown in admin artist detail
     */
    createdAt?: string;
}

