/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArtistResponse } from './artist-response';


export interface ArtistPage { 
    content?: Array<ArtistResponse>;
    totalElements?: number;
    totalPages?: number;
    page?: number;
    size?: number;
}

