/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenreResponse { 
    id?: string;
    name?: string;
    gradientStart?: string;
    gradientEnd?: string;
    /**
     * Number of songs tagged with this genre (computed)
     */
    songCount?: number;
    createdAt?: string;
}

