/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SongInternalDto { 
    id?: string;
    title?: string;
    artistName?: string;
    coverUrl?: string;
    audioUrl?: string;
    /**
     * Song duration in milliseconds
     */
    durationMs?: number;
}

