/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SongResponse } from './song-response';


export interface SongPage { 
    content?: Array<SongResponse>;
    totalElements?: number;
    totalPages?: number;
    page?: number;
    size?: number;
}

