/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SongCreateRequest { 
    title: string;
    artistId: string;
    albumId?: string;
    coverUrl: string;
    audioUrl: string;
    /**
     * Duration in seconds
     */
    duration: number;
    lyrics?: string;
    genreIds?: Array<string>;
}

