/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenreResponse } from './genre-response';
import { AlbumResponse } from './album-response';
import { ArtistResponse } from './artist-response';


export interface SongResponse { 
    id?: string;
    title?: string;
    artist?: ArtistResponse;
    album?: AlbumResponse;
    coverUrl?: string;
    audioUrl?: string;
    duration?: number;
    lyrics?: string;
    playCount?: number;
    likesCount?: number;
    genres?: Array<GenreResponse>;
}

