/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StationRequest { 
    name: string;
    /**
     * Single genre that categorizes this station (shown in detail view)
     */
    genreId: string;
    gradientStart: string;
    gradientEnd: string;
    isActive?: boolean;
    /**
     * Songs directly assigned to this station (minimum 3 required)
     */
    songIds: Array<string>;
}

