/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StationResponse } from './station-response';


export interface StationPage { 
    content?: Array<StationResponse>;
    totalElements?: number;
    totalPages?: number;
    page?: number;
    size?: number;
}

