/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StationResponse { 
    id?: string;
    name?: string;
    genreId?: string;
    genreName?: string;
    gradientStart?: string;
    gradientEnd?: string;
    /**
     * Number of songs directly assigned to this station
     */
    songCount?: number;
    isActive?: boolean;
    createdAt?: string;
    updatedAt?: string;
}

