/**
 * Interaction Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LibraryItemType = 'ALBUM' | 'ARTIST';

export const LibraryItemType = {

    ALBUM: 'ALBUM' as LibraryItemType,

    ARTIST: 'ARTIST' as LibraryItemType
};

