/**
 * Interaction Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LibraryItemType } from './library-item-type';


export interface LibraryRequest { 
    type: LibraryItemType;
    itemId: string;
}
export namespace LibraryRequest {
}


