/**
 * Interaction Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlayHistoryResponse } from './play-history-response';


export interface PlayHistoryPage { 
    content?: Array<PlayHistoryResponse>;
    totalElements?: number;
    totalPages?: number;
    page?: number;
    size?: number;
}

