/**
 * Interaction Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlayHistoryResponse { 
    id?: string;
    songId?: string;
    playedAt?: string;
    durationPlayed?: number;
}

