/**
 * Interaction Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UuidPage { 
    content?: Array<string>;
    totalElements?: number;
    totalPages?: number;
    page?: number;
    size?: number;
}

