/**
 * Social Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FollowStatusResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ArtistFollowsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Follow an artist
     * 
     * @param artistId 
     */
    followArtist(artistId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Check if the authenticated user follows an artist
     * 
     * @param artistId 
     */
    getFollowStatus(artistId: string, extraHttpRequestParams?: any): Observable<FollowStatusResponse>;

    /**
     * Get artist IDs followed by the authenticated user
     * 
     */
    getFollowedArtists(extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * Unfollow an artist
     * 
     * @param artistId 
     */
    unfollowArtist(artistId: string, extraHttpRequestParams?: any): Observable<{}>;

}
