/**
 * Social Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/models';
import { FriendRequestBody } from '../model/models';
import { FriendshipResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FriendshipsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Accept a friend request
     * 
     * @param friendshipId 
     */
    acceptFriendRequest(friendshipId: string, extraHttpRequestParams?: any): Observable<FriendshipResponse>;

    /**
     * List pending incoming friend requests
     * 
     */
    getPendingRequests(extraHttpRequestParams?: any): Observable<Array<FriendshipResponse>>;

    /**
     * List accepted friends for the authenticated user
     * 
     */
    listFriends(extraHttpRequestParams?: any): Observable<Array<FriendshipResponse>>;

    /**
     * Reject a friend request
     * 
     * @param friendshipId 
     */
    rejectFriendRequest(friendshipId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Remove a friend (soft delete — supports Undo)
     * 
     * @param friendshipId 
     */
    removeFriend(friendshipId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Send a friend request (Conectar)
     * 
     * @param friendRequestBody 
     */
    sendFriendRequest(friendRequestBody: FriendRequestBody, extraHttpRequestParams?: any): Observable<FriendshipResponse>;

}
