/**
 * Social Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateReportRequest } from '../model/models';
import { ReportPage } from '../model/models';
import { ReportResponse } from '../model/models';
import { ReportStatsResponse } from '../model/models';
import { ReportStatus } from '../model/models';
import { ReportTargetSummary } from '../model/models';
import { ReportTargetType } from '../model/models';
import { UpdateReportStatusRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReportsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Report a comment, song or user
     * 
     * @param createReportRequest 
     */
    createReport(createReportRequest: CreateReportRequest, extraHttpRequestParams?: any): Observable<ReportResponse>;

    /**
     * Dismiss all pending reports for a target (admin Descartar action)
     * 
     * @param targetId 
     */
    dismissReportsByTarget(targetId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Aggregate report counts for the admin dashboard \&quot;Reportes de Gravedad\&quot; chart
     * 
     */
    getReportStats(extraHttpRequestParams?: any): Observable<ReportStatsResponse>;

    /**
     * Full report history for a specific target (admin detail modal)
     * 
     * @param targetId 
     */
    getReportsByTarget(targetId: string, extraHttpRequestParams?: any): Observable<Array<ReportResponse>>;

    /**
     * List reports grouped by target (admin Reportes panel cards)
     * 
     * @param targetType Filter by target type (USER, SONG, COMMENT). Omit for all.
     * @param status 
     */
    listGroupedReports(targetType?: ReportTargetType, status?: ReportStatus, extraHttpRequestParams?: any): Observable<Array<ReportTargetSummary>>;

    /**
     * List individual reports by status and optional target type (admin only)
     * 
     * @param status 
     * @param targetType 
     * @param page 
     * @param size 
     */
    listReports(status?: ReportStatus, targetType?: ReportTargetType, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ReportPage>;

    /**
     * Update report status (admin only)
     * 
     * @param reportId 
     * @param updateReportStatusRequest 
     */
    updateReportStatus(reportId: string, updateReportStatusRequest: UpdateReportStatusRequest, extraHttpRequestParams?: any): Observable<ReportResponse>;

}
