/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/models';
import { GoogleLoginRequest } from '../model/models';
import { LoginRequest } from '../model/models';
import { RefreshTokenRequest } from '../model/models';
import { TokenResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthenticationApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Login with email and password
     * 
     * @param loginRequest 
     */
    login(loginRequest: LoginRequest, extraHttpRequestParams?: any): Observable<TokenResponse>;

    /**
     * Login or register via Google OAuth
     * 
     * @param googleLoginRequest 
     */
    loginWithGoogle(googleLoginRequest: GoogleLoginRequest, extraHttpRequestParams?: any): Observable<TokenResponse>;

    /**
     * Revoke current refresh token (logout from this device)
     * 
     * @param refreshTokenRequest 
     */
    logout(refreshTokenRequest: RefreshTokenRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Revoke all refresh tokens (logout from all devices)
     * 
     */
    logoutAll(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Issue a new access token using a refresh token
     * 
     * @param refreshTokenRequest 
     */
    refreshToken(refreshTokenRequest: RefreshTokenRequest, extraHttpRequestParams?: any): Observable<TokenResponse>;

}
