/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/models';
import { ServiceTokenRequest } from '../model/models';
import { ServiceTokenResponse } from '../model/models';
import { UserInternalDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InternalApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Fetch minimal user data for internal service consumption
     * 
     * @param id 
     */
    getInternalUserById(id: string, extraHttpRequestParams?: any): Observable<UserInternalDto>;

    /**
     * Fetch multiple users by comma-separated UUIDs (unknown IDs silently omitted)
     * 
     * @param ids Comma-separated list of user UUIDs
     */
    getInternalUsersBatch(ids: string, extraHttpRequestParams?: any): Observable<Array<UserInternalDto>>;

    /**
     * Issue a service JWT for M2M authentication (secret-based)
     * 
     * @param serviceTokenRequest 
     */
    issueServiceToken(serviceTokenRequest: ServiceTokenRequest, extraHttpRequestParams?: any): Observable<ServiceTokenResponse>;

}
