/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/models';
import { PasswordResetBody } from '../model/models';
import { PasswordResetRequestBody } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PasswordApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Request a PASSWORD_RESET OTP by email
     * 
     * @param passwordResetRequestBody 
     */
    requestPasswordReset(passwordResetRequestBody: PasswordResetRequestBody, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Set new password after OTP verification
     * 
     * @param passwordResetBody 
     */
    resetPassword(passwordResetBody: PasswordResetBody, extraHttpRequestParams?: any): Observable<{}>;

}
