/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/models';
import { RegisterRequest } from '../model/models';
import { ResendOtpRequest } from '../model/models';
import { UserResponse } from '../model/models';
import { VerifyOtpRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RegistrationApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Register a new user with email
     * 
     * @param registerRequest 
     */
    register(registerRequest: RegisterRequest, extraHttpRequestParams?: any): Observable<UserResponse>;

    /**
     * Resend OTP to the given email
     * 
     * @param resendOtpRequest 
     */
    resendOtp(resendOtpRequest: ResendOtpRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Verify email with 6-digit OTP (REGISTER or PASSWORD_RESET)
     * 
     * @param verifyOtpRequest 
     */
    verifyEmail(verifyOtpRequest: VerifyOtpRequest, extraHttpRequestParams?: any): Observable<{}>;

}
