/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BatchUsersRequest } from '../model/models';
import { ChangeUserStatusRequest } from '../model/models';
import { ErrorResponse } from '../model/models';
import { UpdateProfileRequest } from '../model/models';
import { UserPage } from '../model/models';
import { UserResponse } from '../model/models';
import { UserStatsResponse } from '../model/models';
import { UserStatus } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Fetch multiple user profiles by ID in one request (for friends list, mentions, etc.)
     * 
     * @param batchUsersRequest 
     */
    batchGetUsers(batchUsersRequest: BatchUsersRequest, extraHttpRequestParams?: any): Observable<Array<UserResponse>>;

    /**
     * Change user account status — Activo / Inactivo / Bloqueado (admin)
     * 
     * @param id 
     * @param changeUserStatusRequest 
     */
    changeUserStatus(id: string, changeUserStatusRequest: ChangeUserStatusRequest, extraHttpRequestParams?: any): Observable<UserResponse>;

    /**
     * Get user profile by ID
     * 
     * @param id 
     */
    getUserById(id: string, extraHttpRequestParams?: any): Observable<UserResponse>;

    /**
     * Aggregate user stats for the admin dashboard (gender distribution, status counts)
     * 
     */
    getUserStats(extraHttpRequestParams?: any): Observable<UserStatsResponse>;

    /**
     * List/search all users (admin — Gestión de Usuarios screen)
     * 
     * @param q Search by display name or email
     * @param status Filter by account status
     * @param page 
     * @param size 
     */
    listUsers(q?: string, status?: UserStatus, page?: number, size?: number, extraHttpRequestParams?: any): Observable<UserPage>;

    /**
     * Update display name and/or profile photo URL
     * 
     * @param id 
     * @param updateProfileRequest 
     */
    updateProfile(id: string, updateProfileRequest: UpdateProfileRequest, extraHttpRequestParams?: any): Observable<UserResponse>;

}
