/**
 * Playlist Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlaylistResponse } from './playlist-response';


export interface PlaylistPage { 
    content?: Array<PlaylistResponse>;
    totalElements?: number;
    totalPages?: number;
    page?: number;
    size?: number;
}

