/**
 * Playlist Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SystemSongRequest { 
    /**
     * ID of the user whose system playlist will be updated
     */
    userId: string;
    /**
     * ID of the song to add
     */
    songId: string;
}

