/**
 * Playlist Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SystemSongRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InternalApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Add a song to the user\&#39;s \&quot;Tus me gusta\&quot; system playlist
     * Called by interaction-service when a user likes a song. Creates the system playlist if it does not exist yet (idempotent). Requires a SERVICE JWT (ROLE_SERVICE). 
     * @param systemSongRequest 
     */
    addSongToSystemPlaylistInternal(systemSongRequest: SystemSongRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Remove a song from the user\&#39;s \&quot;Tus me gusta\&quot; system playlist
     * Called by interaction-service when a user unlikes a song. Idempotent: no-op if the song is not in the system playlist. Requires a SERVICE JWT (ROLE_SERVICE). 
     * @param userId 
     * @param songId 
     */
    removeSongFromSystemPlaylistInternal(userId: string, songId: string, extraHttpRequestParams?: any): Observable<{}>;

}
