/**
 * Playlist Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddSongRequest } from '../model/models';
import { PlaylistSongResponse } from '../model/models';
import { ReorderSongsRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PlaylistSongsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Add a song to a playlist
     * 
     * @param id 
     * @param addSongRequest 
     */
    addSongToPlaylist(id: string, addSongRequest: AddSongRequest, extraHttpRequestParams?: any): Observable<PlaylistSongResponse>;

    /**
     * Get songs in a playlist ordered by position
     * 
     * @param id 
     */
    getPlaylistSongs(id: string, extraHttpRequestParams?: any): Observable<Array<PlaylistSongResponse>>;

    /**
     * Remove a song from a playlist
     * 
     * @param id 
     * @param songId 
     */
    removeSongFromPlaylist(id: string, songId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Reorder all songs in a playlist (drag &amp; drop)
     * 
     * @param id 
     * @param reorderSongsRequest 
     */
    reorderSongs(id: string, reorderSongsRequest: ReorderSongsRequest, extraHttpRequestParams?: any): Observable<{}>;

}
