/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AlbumPage } from '../model/models';
import { AlbumRequest } from '../model/models';
import { AlbumResponse } from '../model/models';
import { SongPage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AlbumsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create album (admin)
     * 
     * @param albumRequest 
     */
    createAlbum(albumRequest: AlbumRequest, extraHttpRequestParams?: any): Observable<AlbumResponse>;

    /**
     * Delete album (admin)
     * 
     * @param id 
     */
    deleteAlbum(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get album by ID
     * 
     * @param id 
     */
    getAlbumById(id: string, extraHttpRequestParams?: any): Observable<AlbumResponse>;

    /**
     * Songs in an album
     * 
     * @param id 
     * @param page 
     * @param size 
     */
    getAlbumSongs(id: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<SongPage>;

    /**
     * New releases ordered by release date
     * 
     * @param page 
     * @param size 
     */
    getNewReleases(page?: number, size?: number, extraHttpRequestParams?: any): Observable<AlbumPage>;

    /**
     * Top albums by total streams
     * 
     * @param page 
     * @param size 
     */
    getTopAlbums(page?: number, size?: number, extraHttpRequestParams?: any): Observable<AlbumPage>;

    /**
     * List albums (paginated, optional artistId filter for admin dropdown)
     * 
     * @param artistId Filter albums by artist (admin filter dropdown)
     * @param page 
     * @param size 
     */
    listAlbums(artistId?: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<AlbumPage>;

    /**
     * Search albums by title
     * 
     * @param q 
     * @param page 
     * @param size 
     */
    searchAlbums(q: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<AlbumPage>;

    /**
     * Update album (admin)
     * 
     * @param id 
     * @param albumRequest 
     */
    updateAlbum(id: string, albumRequest: AlbumRequest, extraHttpRequestParams?: any): Observable<AlbumResponse>;

}
