export * from './albums.service';
import { AlbumsApi } from './albums.service';
export * from './albums.serviceInterface';
export * from './artists.service';
import { ArtistsApi } from './artists.service';
export * from './artists.serviceInterface';
export * from './catalog.service';
import { CatalogApi } from './catalog.service';
export * from './catalog.serviceInterface';
export * from './genres.service';
import { GenresApi } from './genres.service';
export * from './genres.serviceInterface';
export * from './internal.service';
import { InternalApi } from './internal.service';
export * from './internal.serviceInterface';
export * from './songs.service';
import { SongsApi } from './songs.service';
export * from './songs.serviceInterface';
export * from './stations.service';
import { StationsApi } from './stations.service';
export * from './stations.serviceInterface';
export const APIS = [AlbumsApi, ArtistsApi, CatalogApi, GenresApi, InternalApi, SongsApi, StationsApi];
