/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AlbumPage } from '../model/models';
import { ArtistPage } from '../model/models';
import { ArtistRequest } from '../model/models';
import { ArtistResponse } from '../model/models';
import { SongPage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ArtistsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create artist (admin)
     * 
     * @param artistRequest 
     */
    createArtist(artistRequest: ArtistRequest, extraHttpRequestParams?: any): Observable<ArtistResponse>;

    /**
     * Delete artist (admin)
     * 
     * @param id 
     */
    deleteArtist(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Albums by artist
     * 
     * @param id 
     * @param page 
     * @param size 
     */
    getArtistAlbums(id: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<AlbumPage>;

    /**
     * Get artist by ID
     * 
     * @param id 
     */
    getArtistById(id: string, extraHttpRequestParams?: any): Observable<ArtistResponse>;

    /**
     * Songs by artist (top songs)
     * 
     * @param id 
     * @param page 
     * @param size 
     */
    getArtistSongs(id: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<SongPage>;

    /**
     * Get top artists (for onboarding and home sections)
     * 
     */
    getTopArtists(extraHttpRequestParams?: any): Observable<Array<ArtistResponse>>;

    /**
     * List artists (paginated, optional isTop filter for admin \&quot;Solo destacados\&quot;)
     * 
     * @param isTop When true, returns only top/featured artists
     * @param page 
     * @param size 
     */
    listArtists(isTop?: boolean, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ArtistPage>;

    /**
     * Search artists by name
     * 
     * @param q 
     * @param page 
     * @param size 
     */
    searchArtists(q: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ArtistPage>;

    /**
     * Update artist (admin)
     * 
     * @param id 
     * @param artistRequest 
     */
    updateArtist(id: string, artistRequest: ArtistRequest, extraHttpRequestParams?: any): Observable<ArtistResponse>;

}
