/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GetCatalogStats200Response } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CatalogApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Catalog totals for admin dashboard (totalSongs, totalArtists, totalAlbums)
     * 
     */
    getCatalogStats(extraHttpRequestParams?: any): Observable<GetCatalogStats200Response>;

}
