/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GenreRequest } from '../model/models';
import { GenreResponse } from '../model/models';
import { SongPage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GenresApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a genre (admin)
     * 
     * @param genreRequest 
     */
    createGenre(genreRequest: GenreRequest, extraHttpRequestParams?: any): Observable<GenreResponse>;

    /**
     * Delete genre (admin)
     * 
     * @param id 
     */
    deleteGenre(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get genre by ID
     * 
     * @param id 
     */
    getGenreById(id: string, extraHttpRequestParams?: any): Observable<GenreResponse>;

    /**
     * Songs tagged with a given genre (paginated)
     * 
     * @param id 
     * @param page 
     * @param size 
     */
    getSongsByGenre(id: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<SongPage>;

    /**
     * List all genres (optionally filtered by name — admin search bar)
     * 
     * @param q Filter by name (partial match, case-insensitive)
     */
    listGenres(q?: string, extraHttpRequestParams?: any): Observable<Array<GenreResponse>>;

    /**
     * Update genre (admin)
     * 
     * @param id 
     * @param genreRequest 
     */
    updateGenre(id: string, genreRequest: GenreRequest, extraHttpRequestParams?: any): Observable<GenreResponse>;

}
