/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ArtistInternalDto } from '../model/models';
import { SongInternalDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InternalApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get artist by ID — internal service call
     * 
     * @param id 
     */
    getInternalArtistById(id: string, extraHttpRequestParams?: any): Observable<ArtistInternalDto>;

    /**
     * Get song by ID — internal service call
     * 
     * @param id 
     */
    getInternalSongById(id: string, extraHttpRequestParams?: any): Observable<SongInternalDto>;

    /**
     * Get songs by IDs (batch) — internal service call
     * 
     * @param ids Comma-separated list of song UUIDs
     */
    getInternalSongsBatch(ids: string, extraHttpRequestParams?: any): Observable<Array<SongInternalDto>>;

}
