/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SongCreateRequest } from '../model/models';
import { SongPage } from '../model/models';
import { SongResponse } from '../model/models';
import { SongUpdateRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SongsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create song (admin)
     * 
     * @param songCreateRequest 
     */
    createSong(songCreateRequest: SongCreateRequest, extraHttpRequestParams?: any): Observable<SongResponse>;

    /**
     * Delete song (admin)
     * 
     * @param id 
     */
    deleteSong(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 10 most recently added songs — Home \&quot;Escuchar ahora\&quot; + admin dashboard
     * 
     */
    getRecentSongs(extraHttpRequestParams?: any): Observable<Array<SongResponse>>;

    /**
     * Get song recommendations based on a set of reference songs (for \&quot;Canciones recomendadas\&quot; in playlist detail)
     * 
     * @param songIds 
     * @param page 
     * @param size 
     */
    getRecommendations(songIds: Array<string>, page?: number, size?: number, extraHttpRequestParams?: any): Observable<SongPage>;

    /**
     * Get song by ID
     * 
     * @param id 
     */
    getSongById(id: string, extraHttpRequestParams?: any): Observable<SongResponse>;

    /**
     * Songs tagged with a given genre (paginated)
     * 
     * @param id 
     * @param page 
     * @param size 
     */
    getSongsByGenre(id: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<SongPage>;

    /**
     * Songs directly assigned to a station (paginated)
     * 
     * @param id 
     * @param page 
     * @param size 
     */
    getSongsByStation(id: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<SongPage>;

    /**
     * List all songs paginated (admin Canciones panel)
     * 
     * @param page 
     * @param size 
     */
    listSongs(page?: number, size?: number, extraHttpRequestParams?: any): Observable<SongPage>;

    /**
     * Search songs by title or artist name
     * 
     * @param q 
     * @param page 
     * @param size 
     */
    searchSongs(q: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<SongPage>;

    /**
     * Update song (admin)
     * 
     * @param id 
     * @param songUpdateRequest 
     */
    updateSong(id: string, songUpdateRequest: SongUpdateRequest, extraHttpRequestParams?: any): Observable<SongResponse>;

}
