/**
 * Catalog Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SongPage } from '../model/models';
import { StationPage } from '../model/models';
import { StationRequest } from '../model/models';
import { StationResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface StationsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a station (admin)
     * 
     * @param stationRequest 
     */
    createStation(stationRequest: StationRequest, extraHttpRequestParams?: any): Observable<StationResponse>;

    /**
     * Delete station (admin)
     * 
     * @param id 
     */
    deleteStation(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Songs directly assigned to a station (paginated)
     * 
     * @param id 
     * @param page 
     * @param size 
     */
    getSongsByStation(id: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<SongPage>;

    /**
     * Get station by ID
     * 
     * @param id 
     */
    getStationById(id: string, extraHttpRequestParams?: any): Observable<StationResponse>;

    /**
     * List all active stations (Home screen + onboarding picker)
     * 
     */
    listActiveStations(extraHttpRequestParams?: any): Observable<Array<StationResponse>>;

    /**
     * List stations paginated (admin)
     * 
     * @param page 
     * @param size 
     */
    listStations(page?: number, size?: number, extraHttpRequestParams?: any): Observable<StationPage>;

    /**
     * Search active stations by name
     * 
     * @param q 
     * @param page 
     * @param size 
     */
    searchStations(q: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<StationPage>;

    /**
     * Update station (admin)
     * 
     * @param id 
     * @param stationRequest 
     */
    updateStation(id: string, stationRequest: StationRequest, extraHttpRequestParams?: any): Observable<StationResponse>;

}
