/**
 * Social Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportTargetType } from './report-target-type';


export interface CreateReportRequest { 
    targetType: ReportTargetType;
    targetId: string;
    reason?: string;
}
export namespace CreateReportRequest {
}


