/**
 * Social Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FriendshipStatus } from './friendship-status';


export interface FriendshipResponse { 
    id?: string;
    requesterId?: string;
    addresseeId?: string;
    status?: FriendshipStatus;
    createdAt?: string;
    updatedAt?: string;
}
export namespace FriendshipResponse {
}


