/**
 * Social Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FriendshipStatus = 'PENDING' | 'ACCEPTED' | 'REJECTED' | 'REMOVED';

export const FriendshipStatus = {

    PENDING: 'PENDING' as FriendshipStatus,

    ACCEPTED: 'ACCEPTED' as FriendshipStatus,

    REJECTED: 'REJECTED' as FriendshipStatus,

    REMOVED: 'REMOVED' as FriendshipStatus
};

