/**
 * Social Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportStatsResponse { 
    total?: number;
    /**
     * Count per ReportStatus (PENDING, REVIEWED, DISMISSED)
     */
    byStatus?: { [key: string]: number; };
    /**
     * Count per ReportTargetType (COMMENT, SONG, USER)
     */
    byTargetType?: { [key: string]: number; };
}

