/**
 * Social Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ReportStatus = 'PENDING' | 'REVIEWED' | 'DISMISSED';

export const ReportStatus = {

    PENDING: 'PENDING' as ReportStatus,

    REVIEWED: 'REVIEWED' as ReportStatus,

    DISMISSED: 'DISMISSED' as ReportStatus
};

