/**
 * Social Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportTargetType } from './report-target-type';


/**
 * Aggregated report info for one target entity (used in admin grouped list)
 */
export interface ReportTargetSummary { 
    targetId?: string;
    targetType?: ReportTargetType;
    /**
     * Total pending reports for this target
     */
    reportCount?: number;
    /**
     * Date of the most recent report
     */
    latestReportAt?: string;
}
export namespace ReportTargetSummary {
}


