/**
 * Social Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportStatus } from './report-status';
import { ReportTargetType } from './report-target-type';


export interface ReportResponse { 
    id?: string;
    reporterId?: string;
    targetType?: ReportTargetType;
    targetId?: string;
    reason?: string;
    status?: ReportStatus;
    createdAt?: string;
}
export namespace ReportResponse {
}


