/**
 * Social Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ReportTargetType = 'COMMENT' | 'SONG' | 'USER';

export const ReportTargetType = {

    COMMENT: 'COMMENT' as ReportTargetType,

    SONG: 'SONG' as ReportTargetType,

    USER: 'USER' as ReportTargetType
};

