/**
 * Social Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportResponse } from './report-response';


export interface ReportPage { 
    content?: Array<ReportResponse>;
    totalElements?: number;
    totalPages?: number;
    page?: number;
    size?: number;
}

