/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AuthProvider = 'EMAIL' | 'GOOGLE';

export const AuthProvider = {

    EMAIL: 'EMAIL' as AuthProvider,

    GOOGLE: 'GOOGLE' as AuthProvider
};

