/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type BlockReason = 'HARASSMENT_OR_BULLYING' | 'INCITEMENT_TO_VIOLENCE' | 'RACISM_OR_DISCRIMINATION' | 'INAPPROPRIATE_CONTENT' | 'SPAM_OR_ADVERTISING';

export const BlockReason = {

    HARASSMENT_OR_BULLYING: 'HARASSMENT_OR_BULLYING' as BlockReason,

    INCITEMENT_TO_VIOLENCE: 'INCITEMENT_TO_VIOLENCE' as BlockReason,

    RACISM_OR_DISCRIMINATION: 'RACISM_OR_DISCRIMINATION' as BlockReason,

    INAPPROPRIATE_CONTENT: 'INAPPROPRIATE_CONTENT' as BlockReason,

    SPAM_OR_ADVERTISING: 'SPAM_OR_ADVERTISING' as BlockReason
};

