/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BlockReason } from './block-reason';
import { UserStatus } from './user-status';


export interface ChangeUserStatusRequest { 
    status: UserStatus;
    blockReason?: BlockReason;
}
export namespace ChangeUserStatusRequest {
}


