/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Gender = 'FEMENINO' | 'MASCULINO' | 'NO_BINARIO' | 'OTRO' | 'PREFER_NOT_SAY';

export const Gender = {

    FEMENINO: 'FEMENINO' as Gender,

    MASCULINO: 'MASCULINO' as Gender,

    NO_BINARIO: 'NO_BINARIO' as Gender,

    OTRO: 'OTRO' as Gender,

    PREFER_NOT_SAY: 'PREFER_NOT_SAY' as Gender
};

