/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Gender } from './gender';


export interface RegisterRequest { 
    email: string;
    password: string;
    displayName: string;
    birthDate: string;
    gender: Gender;
    acceptedTerms: boolean;
    acceptedPrivacyPolicy: boolean;
    acceptsMarketing?: boolean;
}
export namespace RegisterRequest {
}


