/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServiceTokenRequest { 
    /**
     * Unique service identifier (e.g. interaction-service)
     */
    serviceName: string;
    /**
     * Shared secret distributed via config-server
     */
    serviceSecret: string;
}

