/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServiceTokenResponse { 
    /**
     * Signed RS256 JWT with role=SERVICE
     */
    token?: string;
    /**
     * Token validity in seconds
     */
    expiresIn?: number;
}

