/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponse } from './user-response';


export interface UserPage { 
    content?: Array<UserResponse>;
    totalElements?: number;
    totalPages?: number;
    page?: number;
    size?: number;
}

