/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponse } from './user-response';


export interface UserStatsResponse { 
    total?: number;
    /**
     * Count per Gender enum value
     */
    byGender?: { [key: string]: number; };
    /**
     * Count per UserStatus enum value
     */
    byStatus?: { [key: string]: number; };
    /**
     * 10 most recently registered users for the dashboard widget
     */
    recentUsers?: Array<UserResponse>;
}

