/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserRole = 'USER' | 'ADMIN';

export const UserRole = {

    USER: 'USER' as UserRole,

    ADMIN: 'ADMIN' as UserRole
};

