/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BlockReason } from './block-reason';
import { UserRole } from './user-role';
import { AuthProvider } from './auth-provider';
import { Gender } from './gender';
import { UserStatus } from './user-status';


export interface UserResponse { 
    id?: string;
    email?: string;
    displayName?: string;
    birthDate?: string;
    gender?: Gender;
    authProvider?: AuthProvider;
    profilePhotoUrl?: string;
    isEmailVerified?: boolean;
    role?: UserRole;
    status?: UserStatus;
    blockReason?: BlockReason;
    createdAt?: string;
}
export namespace UserResponse {
}


