/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserStatus = 'ACTIVE' | 'INACTIVE' | 'BLOCKED';

export const UserStatus = {

    ACTIVE: 'ACTIVE' as UserStatus,

    INACTIVE: 'INACTIVE' as UserStatus,

    BLOCKED: 'BLOCKED' as UserStatus
};

