/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserInternalDto { 
    id?: string;
    email?: string;
    /**
     * User display name (mapped from displayName)
     */
    username?: string;
    profilePhotoUrl?: string;
    status?: UserInternalDto.StatusEnum;
}
export namespace UserInternalDto {
    export type StatusEnum = 'ACTIVE' | 'INACTIVE' | 'BLOCKED';
    export const StatusEnum = {
        ACTIVE: 'ACTIVE' as StatusEnum,
        INACTIVE: 'INACTIVE' as StatusEnum,
        BLOCKED: 'BLOCKED' as StatusEnum
    };
}


