/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VerificationType } from './verification-type';


export interface VerifyOtpRequest { 
    email: string;
    code: string;
    type: VerificationType;
}
export namespace VerifyOtpRequest {
}


