/**
 * Auth Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type VerificationType = 'REGISTER' | 'PASSWORD_RESET';

export const VerificationType = {

    REGISTER: 'REGISTER' as VerificationType,

    PASSWORD_RESET: 'PASSWORD_RESET' as VerificationType
};

