/**
 * Interaction Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UserLikesInternalResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InternalApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get liked song IDs for a user (service-to-service)
     * 
     * @param userId 
     * @param page 
     * @param size 
     */
    getUserLikes(userId: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<UserLikesInternalResponse>;

}
