/**
 * Interaction Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PlayHistoryPage } from '../model/models';
import { RecordPlayRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PlayHistoryApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get play history for the authenticated user (paginated)
     * 
     * @param page 
     * @param size 
     */
    getPlayHistory(page?: number, size?: number, extraHttpRequestParams?: any): Observable<PlayHistoryPage>;

    /**
     * Record a song play
     * 
     * @param recordPlayRequest 
     */
    recordPlay(recordPlayRequest: RecordPlayRequest, extraHttpRequestParams?: any): Observable<{}>;

}
