/**
 * Interaction Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UuidListRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PreferencesApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get selected artist IDs for the authenticated user
     * 
     */
    getArtistPreferences(extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * Get selected genre IDs for the authenticated user
     * 
     */
    getGenrePreferences(extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * Get selected station IDs for the authenticated user
     * 
     */
    getStationPreferences(extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * Save artist preferences (replaces existing)
     * 
     * @param uuidListRequest 
     */
    saveArtistPreferences(uuidListRequest: UuidListRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Save genre preferences (replaces existing)
     * 
     * @param uuidListRequest 
     */
    saveGenrePreferences(uuidListRequest: UuidListRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Save station preferences (replaces existing — used in onboarding picker)
     * 
     * @param uuidListRequest 
     */
    saveStationPreferences(uuidListRequest: UuidListRequest, extraHttpRequestParams?: any): Observable<{}>;

}
