/**
 * Interaction Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LikeStatusResponse } from '../model/models';
import { UuidPage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SongInteractionsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get hidden song IDs for an album
     * 
     * @param albumId 
     */
    getHiddenSongs(albumId: string, extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * Check if the authenticated user has liked a song
     * 
     * @param songId 
     */
    getLikeStatus(songId: string, extraHttpRequestParams?: any): Observable<LikeStatusResponse>;

    /**
     * Get liked song IDs (paginated)
     * 
     * @param page 
     * @param size 
     */
    getLikedSongs(page?: number, size?: number, extraHttpRequestParams?: any): Observable<UuidPage>;

    /**
     * Hide a song within a specific album
     * 
     * @param albumId 
     * @param songId 
     */
    hideSong(albumId: string, songId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Like a song
     * 
     * @param songId 
     */
    likeSong(songId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Unhide a song (Undo)
     * 
     * @param albumId 
     * @param songId 
     */
    unhideSong(albumId: string, songId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Unlike a song
     * 
     * @param songId 
     */
    unlikeSong(songId: string, extraHttpRequestParams?: any): Observable<{}>;

}
